### ISSUE TITLE
OS translator II misses out areas

### ISSUE THREAD

**Issue by gisjeske** [lutraconsulting/ostranslator-ii#18]
When using the translator on the recent Mastermap Topo data, it misses out some chunks around the boundary (see attached image). The original data is complete so these areas are dropped somewhere in the translator.

![missing_areas](https://cloud.githubusercontent.com/assets/18032544/14024911/79be7b12-f1e3-11e5-9a8b-d86b29df9858.jpg)

**Comment by mostlyAtNight** [comment]
Hi there,

Does the issue also occur if you import a single tile?  if so then I should be able to reproduce the issue here and therefore fix it.  

If that's the case, could you send me a smallish .gml.gz file?

Kind regards,

Pete

**Comment by gisjeske** [comment]
Hi Pete,

Thank you for getting back to me. Yes, the areas that are 'left out' are also not loaded if I load just that one tile. I noticed the tiles that are 'left out' are tiles that are not covering the whole tile area (because they are cut by my areas boundary), maybe that might have something to do with it? 

Please find a tile for testing attached.

Many thanks,
Jeske
[7214215-NT6370-10i43.gz](https://github.com/lutraconsulting/ostranslator-ii/files/220722/7214215-NT6370-10i43.gz)

**Comment by PeterPetrik** [comment]
`ERROR 1: COPY statement failed.
ERROR:  null value in column "fid" violates not-null constraint
DETAIL:  Failing row contains (30789, null, 10111, 2, 2004-03-04, {Land}, null, 1932.897216, {1994-05-12,2003-11-26}, {New,Position}, {"Natural Environment"}, {Scrub}, Natural, 50, null, 0103000020346C0000010000003F000000B81E85EBBA411641E17A142E818824...).
CONTEXT:  COPY topographicarea, line 1: "0103000020346C0000010000003F000000B81E85EBBA411641E17A142E818824418FC2F528D0411641D7A370BD8B882441EC..."
`

Seems like cropped features are missing fid or it is unreadable by ogr2ogr

**Comment by PeterPetrik** [comment]
`ogr2ogr --config GML_EXPOSE_FID NO` fixes the problem by not creating the fid column at all

**Comment by PeterPetrik** [comment]
fixed
