### ISSUE TITLE
Change in OS style names

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/ostranslator-ii#29]
For schema 7, it is topographicarea.qml, etc but now you have multiple options topographicarea-backdrop.qml, topographicarea-light.qml, topographicarea-standard.qml

I think we should use topographicarea-standard.qml styes.

**Comment by PeterPetrik** [comment]
we do, duplicate of #31

**Comment by PeterPetrik** [comment]
fixed in 1.4.2
