### ISSUE TITLE
QGIS style

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/ostranslator-ii#3]
Do you have style files for the OSMM and ITN datasets? Would it be possible in the future to load these into your database as an option?

**Comment by saberraz** [comment]
We are in conversation with the Ordnance Survey and hopefully will be able to get their styles included in the plugin.

Loading local QML files can also be an option for future releases.

**Comment by sangel667** [comment]
Good morning,

As part of a project that I have been working on, I have started exploring your OS Translator Plugin on QGIS, after following your online instructions, when it came to styling the layers according to the OS Style, the layers became not visible, it seems that one of the columns in the script does not comply with one of the columns on the tables. Can you please let me know whether this has been rectified?

Kind Regards
Stathis

**Comment by saberraz** [comment]
It has been fixed. Make sure your QGIS can access internet. This is an issue if you are behind proxy.
