### ISSUE TITLE
Comparison of data Translator 2 vs Astun Loader

### ISSUE THREAD

**Issue by geosmiles** [lutraconsulting/ostranslator-ii#5]
Attached are two pictures of the same ITN data loaded via the Astun Loader and Translator 2. As you can see Translator has put some of the ITN data down off the Cornish cost. 

If you want any more data from my PG, then let me know 

Si 

![astun_loader](https://cloud.githubusercontent.com/assets/4700241/6346633/97dcedb0-bc09-11e4-9e6f-972dd559f3b7.png)
![translator 2](https://cloud.githubusercontent.com/assets/4700241/6346634/9964c0d6-bc09-11e4-8f7a-5340e61ae76f.png)

**Comment by mostlyAtNight** [comment]
Hi Si,

Thanks for the info - that's very useful.  

Those features seem to be coming in at 0,0  According to the OS data schema these should be geometry-less features (I believe) but we have actually specified them as point data to work around a problem we had with the underlying ogr2ogr tool.  

As a workaround you should be able to simply treat these layers as if they were tabular-only layers (without geometry).  

We'll look into a more elegant workaround in upcoming releases.

**Comment by mixedbredie** [comment]
I can confirm this too - ferrynode, roadnode, roadlinkinformation all have features at 0,0.  They are all features with fid/toid like "osgb----------------" and versiondate of 1970-01-01 and, importantly, an ogc_fid of 1.  Is this the first feature created or the template or header row?

**Comment by mostlyAtNight** [comment]
Hi mixedbredie,

Thanks for the additional info - these are indeed a template feature which 'should' have been automatically deleted but it looks like this hasn't occurred - I'll look into it...

**Comment by mostlyAtNight** [comment]
Hi there,

I've just tried to reproduce the problem using a small sample dataset with no luck.  

Can you confirm which version you're using please?

**Comment by mixedbredie** [comment]
My versions:
QGIS 2.6.1 32bit
OS translator II plugin v1.0
PostgreSQL 9.3.4
PostGIS 2.1.2
pgRouting 2.0.0
I think the ITN GML is v7 but not sure. It is a recent extract - Jan 2015.

**Comment by mixedbredie** [comment]
Yeah - GML is v7
*xsi:schemaLocation='http://www.ordnancesurvey.co.uk/xml/namespaces/osgb http://www.ordnancesurvey.co.uk/xml/schema/v7/OSDNFFeatures.xsd'
fid='GDS-6348787-NONGEO'>*
