### ISSUE TITLE
Error :  some import jobs did not complete successfully.

### ISSUE THREAD

**Issue by Rajnikant007** [lutraconsulting/ostranslator-ii#55]
Hi,
I am getting following error while importing GML to PostGIS using QGIS(OS Terminal 2) . I am using QGIS 3.24 version. Can someone help me to resolve the same.

Error : 
Warning: 1 import jobs failed:

  Args: ['-append', '-f', 'PostgreSQL', '--config', 'PG_USE_COPY', 'YES', '--config', 'GML_GFS_TEMPLATE', 'C:\\Users\\RAJNIK~1.SOL\\AppData\\Local\\Temp\\1660741012.8020465.gfs', "PG:dbname='postgis_test_db' host='localhost' port='5432' active_schema=public_tmp user='postgres' password='admin'", 'D:/temp/opmplc_gml3_ss/OS OpenMap Local (GML) SS/data\\SS.gml']
  Stdout: b''
  Stderr: b"FAILURE:\r\nUnable to open datasource `D:/temp/opmplc_gml3_ss/OS OpenMap Local (GML) SS/data\\SS.gml' with the following drivers.\r\n  -> `JP2ECW'\r\n  -> `BAG'\r\n  -> `OCI'\r\n  -> `SOSI'\r\n  -> `PCIDSK'\r\n  -> `netCDF'\r\n  -> `PDS4'\r\n  -> `VICAR'\r\n  -> `JP2OpenJPEG'\r\n  -> `PDF'\r\n  -> `MBTiles'\r\n  -> `EEDA'\r\n  -> `OGCAPI'\r\n  -> `DB2ODBC'\r\n  -> `ESRI Shapefile'\r\n  -> `MapInfo File'\r\n  -> `UK .NTF'\r\n  -> `LVBAG'\r\n  -> `OGR_SDTS'\r\n  -> `S57'\r\n  -> `DGN'\r\n  -> `OGR_VRT'\r\n  -> `REC'\r\n  -> `Memory'\r\n  -> `CSV'\r\n  -> `NAS'\r\n  -> `GML'\r\n  -> `GPX'\r\n  -> `LIBKML'\r\n  -> `KML'\r\n  -> `GeoJSON'\r\n  -> `GeoJSONSeq'\r\n  -> `ESRIJSON'\r\n  -> `TopoJSON'\r\n  -> `Interlis 1'\r\n  -> `Interlis 2'\r\n  -> `OGR_GMT'\r\n  -> `GPKG'\r\n  -> `SQLite'\r\n  -> `ODBC'\r\n  -> `WAsP'\r\n  -> `PGeo'\r\n  -> `MSSQLSpatial'\r\n  -> `OGR_OGDI'\r\n  -> `PostgreSQL'\r\n  -> `MySQL'\r\n  -> `OpenFileGDB'\r\n  -> `DXF'\r\n  -> `CAD'\r\n  -> `FlatGeobuf'\r\n  -> `Geoconcept'\r\n  -> `GeoRSS'\r\n  -> `GPSTrackMaker'\r\n  -> `VFK'\r\n  -> `PGDUMP'\r\n  -> `OSM'\r\n  -> `GPSBabel'\r\n  -> `OGR_PDS'\r\n  -> `WFS'\r\n  -> `OAPIF'\r\n  -> `Geomedia'\r\n  -> `EDIGEO'\r\n  -> `SVG'\r\n  -> `CouchDB'\r\n  -> `Cloudant'\r\n  -> `Idrisi'\r\n  -> `ARCGEN'\r\n  -> `XLS'\r\n  -> `ODS'\r\n  -> `XLSX'\r\n  -> `Elasticsearch'\r\n  -> `Walk'\r\n  -> `Carto'\r\n  -> `AmigoCloud'\r\n  -> `SXF'\r\n  -> `Selafin'\r\n  -> `JML'\r\n  -> `PLSCENES'\r\n  -> `CSW'\r\n  -> `VDV'\r\n  -> `GMLAS'\r\n  -> `MVT'\r\n  -> `NGW'\r\n  -> `MapML'\r\n  -> `TIGER'\r\n  -> `AVCBin'\r\n  -> `AVCE00'\r\n  -> `HTTP'\r\n"

Warning - some import jobs did not complete successfully.
You opted to apply the default OS style. Please ensure you also set up SVG paths and fonts for those who will be using the layers. See http://www.lutraconsulting.co.uk/products/ostranslator-ii/ for more information.

Loaded in 0.0 hours (27 seconds).

**I am done with settings of SVG path as well**. 
![image](https://user-images.githubusercontent.com/111437534/185140562-a6f59dd8-dedf-49f6-905a-51be6068ea38.png)

**Blank tables create on PostGIS**:

![image](https://user-images.githubusercontent.com/111437534/185142281-f379b06a-eab7-4fb5-abf2-9a107db4bd08.png)

**Comment by saberraz** [comment]
Please try the latest.
