### ISSUE TITLE
Problem with the Postgis connection

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/ostranslator-ii#8]
/*--------------------------------------------------------------
An error has occured while executing Python code:
Traceback (most recent call last):
  File "C:/Users/TTT/.qgis2/python/plugins\OSTranslatorII\os_translator_ii_dialog.py", line 343, in accept
    self.extractPgConnectionDetails()
  File "C:/Users/TTT/.qgis2/python/plugins\OSTranslatorII\os_translator_ii_dialog.py", line 309, in extractPgConnectionDetails
    raise Exception('Details of the selected PostGIS connection could not be found, please check your settings')
Exception: Details of the selected PostGIS connection could not be found, please check your settings

Python version:
2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]

QGIS version:
2.6.0-Brighton Brighton, exported

**Comment by mostlyAtNight** [comment]
Hi there,

When this error occurred, did you have any PostGIS connections configured in QGIS?

Could you try configuring a connection (QGIS: Layer > Add Layer > Add PostGIS Layers... > New) and seeing if this causes the error to cease?

Thanks!

**Comment by mostlyAtNight** [comment]
I was unable to reproduce this error.  

Please feel free to re-open with some steps / instructions to reproduce.
